name: contracts - build -> forge test
on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - "**"
jobs:
  tests:
    concurrency: ci-forge-${{ github.head_ref || github.run_id }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install

      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1.0.9

      - name: Compile contracts
        run: |
          pnpm compile:forge

      - name: Test contracts
        run: |
          pnpm test:forge